@baseUrl = http://localhost:3001/api
@adminUrl = http://localhost:5000/admin/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMTVkNDViOTM3OWI1MGEyNDdhOWE1MiIsImlhdCI6MTYxMjEyNDY4OSwiZXhwIjozMjI0MjUyOTc1fQ.XH5Jub6MpETRDhtwStSWO0TjifSm-yGDrG77dWBXeA8
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMWE4ODc2ZjYwOTRhNDYwNDAwYjNmZSIsImlhdCI6MTYxMjM1MjgzNSwiZXhwIjozMjI0NzA5MjE5fQ.FyKFXxBuQjBnv-1niE1IAiIrqDRwFxqSZZgUjnMepYM

###

GET {{baseUrl}}/news/entertainment
Content-Type: application/json


###

GET {{baseUrl}}/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


###


POST  {{baseUrl}}/user/login HTTP/1.1
Content-Type: application/json

{
    "email":"user1@test.com",
    "password": "password"
}



###


POST  {{baseUrl}}/user/register HTTP/1.1
Content-Type: application/json

{
    "name":"user1",
    "email":"user1@test.com",
    "password": "password"
}


###

GET {{baseUrl}}/blog HTTP/1.1
Content-Type: application/json



###

GET {{baseUrl}}/blog/60171e95ab58ba439c33c683 HTTP/1.1
Content-Type: application/json

###


POST  {{baseUrl}}/blogs HTTP/1.1
Content-Type: application/json

{
    "name":"jimmy",
    "title":"Not getting your first job as a jr Dev",
    "content":"Est ea cupidatat veniam consequat eiusmod reprehenderit cillum qui adipisicing ullamco laborum. Nisi dolor amet ad est non amet dolor eiusmod incididunt eu commodo exercitation irure occaecat. Irure veniam non fugiat minim aute amet in elit duis eu ex qui amet. Et cupidatat minim incididunt sint mollit ad minim anim."
} 


###

GET {{adminUrl}}/ HTTP/1.1
Content-Type: application/json
Authorization: AdminBearer {{adminToken}}


###


POST  {{adminUrl}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "bob",
    "password":"password"
}

###


POST  {{adminUrl}}/register HTTP/1.1
Content-Type: application/json

{
    "user": "601324f0843d13413cdfd013",
    "username": "bob",
    "password":"password"
}

###

GET {{adminUrl}}/blogs HTTP/1.1
Content-Type: application/json




###


POST  {{adminUrl}}/blogs HTTP/1.1
Content-Type: application/json

{
    "name":"Chad",
    "title":"Living on a sailboat as a software enginer part 2",
    "featured": true,
    "content":"Est ea cupidatat veniam consequat eiusmod reprehenderit cillum qui adipisicing ullamco laborum. Nisi dolor amet ad est non amet dolor eiusmod incididunt eu commodo exercitation irure occaecat. Irure veniam non fugiat minim aute amet in elit duis eu ex qui amet. Et cupidatat minim incididunt sint mollit ad minim anim."
}

###