@baseUrl = http://localhost:3001/api
@adminUrl = http://localhost:5000


###

GET {{baseUrl}}/user HTTP/1.1
Content-Type: application/json


###


POST  {{baseUrl}}/user HTTP/1.1
Content-Type: application/json

{
    "name":"jimmy",
    "title":"boss"
}

###

GET {{baseUrl}}/blog HTTP/1.1
Content-Type: application/json


###


POST  {{baseUrl}}/blog HTTP/1.1
Content-Type: application/json

{
    "name":"jimmy",
    "title":"boss"
} 


###

GET {{adminUrl}} HTTP/1.1
Content-Type: application/json


###


POST  {{adminUrl}}/ HTTP/1.1
Content-Type: application/json

{
 "user": "601324f0843d13413cdfd013"
}